# Site Settings
title: Kaushik Ghosh web Résumé
url: 'https://kaushik.github.io'
baseurl: '/online-cv' # Change it according to your repository name
description: Curriculum Vitae of Kaushik Ghosh
theme: minima # Specify your theme here if not minima
theme_skin: berry # blue turquoise green berry orange ceramic
chrome_mobile_color: '' # Use hex colors (ex: #1976d2) or leave empty if you don't want a color for chrome mobile search bar

# Tracker
analytics: UA-83979019-1

# Markdown Processor
markdown: kramdown

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
  envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
